{-# LANGUAGE DeriveGeneric #-}

module Words where

import Data.Aeson (FromJSON, ToJSON)
import GHC.Generics (Generic)

-- Estrutura para representar palavras e dicas
data Entry = Entry
  { word :: String
  , hint :: String
  } deriving (Show, Generic, Eq)

instance ToJSON Entry
instance FromJSON Entry

-- Lista de palavras fixas
entries :: [Entry]
entries =
  [ Entry "ABACAXI" "Fruta tropical de casca espinhosa"
  , Entry "ABACATE" "Fruta verde cremosa"
  , Entry "ABELHA" "Inseto que produz mel"
  , Entry "ABRACO" "Gesto de carinho com os braços"
  , Entry "ABRIL" "Quarto mês do ano"
  , Entry "ACUCAR" "Substância doce"
  , Entry "AGUA" "Líquido transparente essencial à vida"
  , Entry "AGUIA" "Ave de rapina majestosa"
  , Entry "ALEGRIA" "Sentimento de felicidade"
  , Entry "ALFACE" "Verdura de folhas verdes"
  , Entry "ALHO" "Tempero aromático"
  , Entry "AMANHA" "O dia que vem depois de hoje"
  , Entry "AMIGO" "Pessoa próxima e querida"
  , Entry "AMOR" "Sentimento profundo de afeto"
  , Entry "AMORA" "Fruta pequena e roxa"
  , Entry "ANCORA" "Objeto pesado para parar embarcações"
  , Entry "ANJO" "Ser celestial"
  , Entry "ANO" "Período de doze meses"
  , Entry "ANEL" "Joia circular para o dedo"
  , Entry "ARVORE" "Planta grande com tronco"
  , Entry "AZUL" "Cor do céu"
  , Entry "BALA" "Doce pequeno"
  , Entry "BANANA" "Fruta amarela alongada"
  , Entry "BARCO" "Embarcação pequena"
  , Entry "BEIJO" "Gesto de carinho com os lábios"
  , Entry "BICICLETA" "Meio de transporte com duas rodas"
  , Entry "BOLO" "Doce assado"
  , Entry "BONECA" "Brinquedo em forma de pessoa"
  , Entry "BORBOLETA" "Inseto colorido com asas"
  , Entry "BRANCO" "Cor da neve"
  , Entry "BRINCO" "Acessório para a orelha"
  , Entry "CABECA" "Parte superior do corpo"
  , Entry "CABELO" "Fios que crescem na cabeça"
  , Entry "CACHORRO" "Animal doméstico fiel"
  , Entry "CAFE" "Bebida escura estimulante"
  , Entry "CAIXA" "Recipiente para guardar coisas"
  , Entry "CAMISA" "Peça de roupa para o tronco"
  , Entry "CANETA" "Instrumento para escrever"
  , Entry "CARACOL" "Molusco com concha espiral"
  , Entry "CARRO" "Veículo automotor"
  , Entry "CASA" "Local onde moramos"
  , Entry "CAVALO" "Animal mamífero usado para transporte"
  , Entry "CEBOLA" "Vegetal que faz chorar"
  , Entry "CELULAR" "Telefone portátil"
  , Entry "CEU" "Espaço azul sobre nossas cabeças"
  , Entry "CHUVA" "Água que cai das nuvens"
  , Entry "CINEMA" "Local para assistir filmes"
  , Entry "COBRA" "Réptil sem pernas"
  , Entry "CORACAO" "Órgão que bombeia sangue"
  , Entry "CORPO" "Estrutura física do ser vivo"
  , Entry "DANCA" "Arte de se mover no ritmo da música"
  , Entry "DEDO" "Extremidade da mão ou pé"
  , Entry "DENTE" "Parte dura usada para mastigar"
  , Entry "DIA" "Período de 24 horas"
  , Entry "DIAMANTE" "Pedra preciosa muito dura"
  , Entry "DINHEIRO" "Meio de pagamento"
  , Entry "DOCE" "Sabor açucarado"
  , Entry "DOMINGO" "Primeiro dia da semana"
  , Entry "DRAGAO" "Criatura mítica que cospe fogo"
  , Entry "ELEFANTE" "Grande mamífero terrestre"
  , Entry "ELEVADOR" "Aparelho para subir andares"
  , Entry "ENERGIA" "Força que move as coisas"
  , Entry "ESCADA" "Estrutura para subir"
  , Entry "ESCOLA" "Lugar de estudo"
  , Entry "ESPELHO" "Superfície que reflete imagem"
  , Entry "ESTRELA" "Corpo celeste brilhante"
  , Entry "FACA" "Utensílio cortante"
  , Entry "FAMILIA" "Pessoas que vivem juntas"
  , Entry "FARINHA" "Pó feito de grãos moídos"
  , Entry "FESTA" "Celebração alegre"
  , Entry "FIGO" "Fruta doce e macia"
  , Entry "FLOR" "Parte colorida da planta"
  , Entry "FOGO" "Combustão visível"
  , Entry "FOLHA" "Parte verde da planta"
  , Entry "FORMIGA" "Inseto pequeno e trabalhador"
  , Entry "FRANGO" "Ave doméstica comestível"
  , Entry "FRIO" "Baixa temperatura"
  , Entry "FRUTA" "Alimento doce das plantas"
  , Entry "GATO" "Animal doméstico felino"
  , Entry "GELO" "Água congelada"
  , Entry "GIRAFA" "Animal alto de pescoço comprido"
  , Entry "GOLFINHO" "Mamífero marinho inteligente"
  , Entry "GRAMA" "Planta verde que cresce no chão"
  , Entry "GUITARRA" "Instrumento musical de cordas"
  , Entry "HELICOPTERO" "Aeronave com hélices"
  , Entry "HIPOPOTAMO" "Grande mamífero herbívoro aquático"
  , Entry "HISTORIA" "Relato de eventos passados"
  , Entry "HOMEM" "Ser humano masculino"
  , Entry "HORA" "Período de sessenta minutos"
  , Entry "HOSPITAL" "Local de tratamento médico"
  , Entry "HOTEL" "Local de hospedagem"
  , Entry "IGREJA" "Edifício religioso"
  , Entry "ILHA" "Porção de terra cercada de água"
  , Entry "INSETO" "Pequeno animal artrópode"
  , Entry "INVERNO" "Estação mais fria do ano"
  , Entry "IRMAO" "Filho dos mesmos pais"
  , Entry "JARDIM" "Espaço com plantas cultivadas"
  , Entry "JANELA" "Abertura em uma parede"
  , Entry "JACARE" "Réptil aquático com dentes grandes"
  , Entry "JOELHO" "Articulação da perna"
  , Entry "JOGO" "Atividade lúdica"
  , Entry "JORNAL" "Publicação com notícias"
  , Entry "LAGARTO" "Réptil rápido"
  , Entry "LAGO" "Corpo de água doce"
  , Entry "LARANJA" "Fruta cítrica alaranjada"
  , Entry "LEAO" "Grande felino carnívoro"
  , Entry "LEITE" "Líquido branco nutritivo"
  , Entry "LIVRO" "Conjunto de páginas com texto"
  , Entry "LOBO" "Canino selvagem"
  , Entry "LUA" "Satélite natural da Terra"
  , Entry "LUVA" "Proteção para as mãos"
  , Entry "MACACO" "Animal primata"
  , Entry "MADEIRA" "Material das árvores"
  , Entry "MAE" "Mulher que teve filhos"
  , Entry "MAGO" "Pessoa que faz mágica"
  , Entry "MALA" "Bagagem para viagem"
  , Entry "MANHA" "Primeira parte do dia"
  , Entry "MAR" "Grande massa de água salgada"
  , Entry "MESA" "Móvel para refeições ou trabalho"
  , Entry "METRO" "Unidade de medida"
  , Entry "MILHO" "Cereal amarelo em espiga"
  , Entry "MONTANHA" "Elevação natural do terreno"
  , Entry "MUSICA" "Arte dos sons organizados"
  , Entry "NARIZ" "Órgão do olfato"
  , Entry "NAVIO" "Transporte marítimo"
  , Entry "NEVE" "Precipitação congelada"
  , Entry "NINHO" "Casa dos pássaros"
  , Entry "NOITE" "Período escuro do dia"
  , Entry "NORTE" "Uma das direções cardeais"
  , Entry "NUMERO" "Símbolo matemático"
  , Entry "NUVEM" "Massa de vapor no céu"
  , Entry "OCULOS" "Acessório para melhorar a visão"
  , Entry "OLHO" "Órgão da visão"
  , Entry "ONCA" "Felino selvagem manchado"
  , Entry "ORELHA" "Órgão da audição"
  , Entry "OURO" "Metal precioso dourado"
  , Entry "OSSO" "Estrutura rígida do esqueleto"
  , Entry "OVO" "Alimento de diversas aves"
  , Entry "PAIXAO" "Amor intenso"
  , Entry "PALHACO" "Artista que diverte"
  , Entry "PAO" "Alimento feito de farinha"
  , Entry "PAPAI" "Forma carinhosa de chamar o pai"
  , Entry "PAPEL" "Material para escrever"
  , Entry "PARQUE" "Área verde de lazer"
  , Entry "PASSARO" "Ave que voa"
  , Entry "PASTA" "Recipiente para documentos"
  , Entry "PATO" "Ave aquática"
  , Entry "PEIXE" "Animal aquático com guelras"
  , Entry "PERNA" "Membro inferior do corpo"
  , Entry "PESSOA" "Ser humano"
  , Entry "PIANO" "Instrumento musical de teclas"
  , Entry "PIPOCA" "Milho estourado"
  , Entry "PLANETA" "Corpo celeste que orbita o sol"
  , Entry "PLANTA" "Ser vivo que faz fotossíntese"
  , Entry "POLICIA" "Força de segurança pública"
  , Entry "POMBO" "Ave comum nas cidades"
  , Entry "PONTE" "Estrutura sobre rio ou vale"
  , Entry "PORTA" "Abertura de entrada"
  , Entry "PRAIA" "Faixa de areia junto ao mar"
  , Entry "PRESENTE" "Dádiva ou tempo atual"
  , Entry "QUEIJO" "Alimento derivado do leite"
  , Entry "QUADRO" "Superfície para escrever ou arte"
  , Entry "RAINHA" "Esposa do rei ou abelha líder"
  , Entry "RATO" "Roedor pequeno"
  , Entry "RELOGIO" "Instrumento que marca o tempo"
  , Entry "RIO" "Curso de água natural"
  , Entry "RODA" "Peça circular que gira"
  , Entry "ROSA" "Flor perfumada com espinhos"
  , Entry "ROSTO" "Face, parte frontal da cabeça"
  , Entry "RUA" "Caminho pavimentado na cidade"
  , Entry "SABAO" "Produto para limpeza"
  , Entry "SAPATO" "Calçado para os pés"
  , Entry "SARDINHA" "Peixe pequeno"
  , Entry "SAUDE" "Estado de bem-estar físico"
  , Entry "SEDE" "Necessidade de beber líquido"
  , Entry "SEMENTE" "Grão que origina nova planta"
  , Entry "SINO" "Instrumento que produz som"
  , Entry "SOL" "Estrela do nosso sistema"
  , Entry "SONHO" "Visão durante o sono"
  , Entry "SORRISO" "Expressão de alegria"
  , Entry "TAMPA" "Cobertura para recipientes"
  , Entry "TARTARUGA" "Réptil com casco"
  , Entry "TEATRO" "Local de apresentações"
  , Entry "TELEFONE" "Aparelho de comunicação"
  , Entry "TEMPO" "Duração dos eventos"
  , Entry "TERRA" "Planeta onde vivemos"
  , Entry "TIGRE" "Grande felino listrado"
  , Entry "TOMATE" "Fruto vermelho comestível"
  , Entry "TRABALHO" "Atividade profissional"
  , Entry "TREM" "Transporte sobre trilhos"
  , Entry "TURMA" "Grupo de pessoas"
  , Entry "ULTIMO" "Que vem por fim"
  , Entry "UNIVERSO" "Conjunto de tudo que existe"
  , Entry "URSO" "Grande mamífero carnívoro"
  , Entry "UVA" "Fruta em cachos"
  , Entry "VACA" "Animal produtor de leite"
  , Entry "VAPOR" "Água em estado gasoso"
  , Entry "VENTO" "Ar em movimento"
  , Entry "VERDE" "Cor das folhas"
  , Entry "VIAGEM" "Deslocamento para outro local"
  , Entry "VIDRO" "Material transparente"
  , Entry "VIOLAO" "Instrumento musical de cordas"
  , Entry "XICARA" "Recipiente para beber"
  , Entry "XADREZ" "Jogo de tabuleiro estratégico"
  , Entry "XALE" "Peça de roupa para cobrir ombros"
  , Entry "ZEBRA" "Animal listrado"
  , Entry "ZANGAO" "Abelha macho"
  , Entry "ZOOLOGICO" "Local com animais para visitação"
  , Entry "ABOBORA" "Fruto alaranjado usado no Halloween"
  , Entry "ACADEMIA" "Local para exercitar-se"
  , Entry "ACIDENTE" "Evento inesperado e indesejado"
  , Entry "ADOLESCENTE" "Pessoa entre infância e idade adulta"
  , Entry "AEROPORTO" "Local de embarque de aviões"
  , Entry "AGENDA" "Livro para anotar compromissos"
  , Entry "AGRICULTURA" "Cultivo de plantas para alimento"
  , Entry "ALCOOL" "Substância líquida inflamável"
  , Entry "ALFABETO" "Conjunto de letras de uma língua"
  , Entry "ALGODAO" "Fibra natural macia"
  , Entry "ALMOCO" "Refeição do meio do dia"
  , Entry "ALTURA" "Medida vertical"
  , Entry "AMBULANCIA" "Veículo para emergências médicas"
  , Entry "AMIZADE" "Relação de carinho entre pessoas"
  , Entry "ANIMAL" "Ser vivo que não é planta"
  , Entry "APARTAMENTO" "Moradia em edifício"
  , Entry "AQUARIO" "Recipiente com água para peixes"
  , Entry "ARQUITETO" "Profissional que projeta construções"
  , Entry "ARROZ" "Cereal branco básico da alimentação"
  , Entry "ARTISTA" "Pessoa que cria arte"
  , Entry "ATLETISMO" "Esporte com corridas e saltos"
  , Entry "AVIAO" "Aeronave com asas fixas"
  , Entry "BANHEIRO" "Cômodo para higiene pessoal"
  , Entry "BARBEIRO" "Profissional que corta cabelo"
  , Entry "BATATA" "Tubérculo comestível"
  , Entry "BIBLIOTECA" "Local com muitos livros"
  , Entry "BIOLOGIA" "Ciência que estuda a vida"
  , Entry "BISCOITO" "Alimento seco e crocante"
  , Entry "BRASIL" "País sul-americano"
  , Entry "BURACO" "Abertura ou cavidade"
  , Entry "CABINE" "Compartimento pequeno"
  , Entry "CADEIRA" "Móvel para sentar"
  , Entry "CALENDARIO" "Sistema de contagem dos dias"
  , Entry "CAMERA" "Aparelho para fotografar"
  , Entry "CANTAR" "Emitir sons musicais"
  , Entry "CAPITAL" "Cidade principal de um país"
  , Entry "CARPINTEIRO" "Profissional que trabalha com madeira"
  , Entry "CARTAO" "Papel ou plástico com informações"
  , Entry "CASTELO" "Construção fortificada antiga"
  , Entry "CEBRA" "Forma alternativa de zebra"
  , Entry "CENOURA" "Legume alaranjado"
  , Entry "CERVEJA" "Bebida alcoólica fermentada"
  , Entry "CHAVE" "Objeto para abrir fechaduras"
  , Entry "CHOCOLATE" "Doce feito de cacau"
  , Entry "CIENCIA" "Conhecimento sistemático"
  , Entry "CIDADE" "Aglomerado urbano"
  , Entry "CIRCO" "Espetáculo com artistas diversos"
  , Entry "COELHO" "Mamífero de orelhas compridas"
  , Entry "COLHER" "Utensílio para comer"
  , Entry "COMPUTADOR" "Máquina eletrônica de processar dados"
  , Entry "CONHECIMENTO" "Informação adquirida"
  , Entry "COZINHA" "Local para preparar alimentos"
  , Entry "CRIANCA" "Pessoa em desenvolvimento"
  , Entry "CULTURA" "Conjunto de tradições de um povo"
  , Entry "DENTISTA" "Profissional que cuida dos dentes"
  , Entry "DESERTO" "Região árida com pouca vegetação"
  , Entry "DIAMANTINA" "Cidade ou relativo a diamante"
  , Entry "DINOSSAURO" "Réptil pré-histórico extinto"
  , Entry "DIRETOR" "Pessoa que dirige uma instituição"
  , Entry "DOUTOR" "Pessoa com título de doutorado"
  , Entry "ECONOMIA" "Sistema de produção e consumo"
  , Entry "EDUCACAO" "Processo de ensino e aprendizagem"
  , Entry "ELETRICIDADE" "Forma de energia"
  , Entry "EMPREGO" "Ocupação remunerada"
  , Entry "ENGENHEIRO" "Profissional de engenharia"
  , Entry "ESCRITORIO" "Local de trabalho administrativo"
  , Entry "ESPORTE" "Atividade física competitiva"
  , Entry "ESTACAO" "Período do ano ou local de parada"
  , Entry "ESTUDANTE" "Pessoa que estuda"
  , Entry "FABRICAR" "Produzir algo industrialmente"
  , Entry "FAZENDA" "Propriedade rural"
  , Entry "FELICIDADE" "Estado de contentamento"
  , Entry "FERRAMENTA" "Instrumento de trabalho"
  , Entry "FOTOGRAFIA" "Arte de capturar imagens"
  , Entry "FUTEBOL" "Esporte com bola nos pés"
  , Entry "GARAGEM" "Local para guardar veículos"
  , Entry "GEOGRAFIA" "Ciência que estuda a Terra"
  , Entry "GOVERNO" "Sistema de administração pública"
  , Entry "GUERRA" "Conflito armado entre nações"
  , Entry "HABITACAO" "Local onde se vive"
  , Entry "HAMBURGUER" "Sanduíche com carne"
  , Entry "HISTORIA" "Estudo dos eventos passados"
  , Entry "HONESTIDADE" "Qualidade de ser honesto"
  , Entry "IDADE" "Tempo de vida de alguém"
  , Entry "IDIOMA" "Língua falada por um povo"
  , Entry "INDUSTRIA" "Setor de produção manufatureira"
  , Entry "INFANCIA" "Período inicial da vida"
  , Entry "INTELIGENCIA" "Capacidade de compreender"
  , Entry "INTERNET" "Rede mundial de computadores"
  , Entry "JANTAR" "Refeição da noite"
  , Entry "JOVEM" "Pessoa em idade juvenil"
  , Entry "JUSTICA" "Princípio da equidade"
  , Entry "LABORATORIO" "Local de experimentos científicos"
  , Entry "LINGUAGEM" "Sistema de comunicação"
  , Entry "LITERATURA" "Arte da palavra escrita"
  , Entry "LOJA" "Estabelecimento comercial"
  , Entry "MAQUINA" "Dispositivo mecânico"
  , Entry "MEDICINA" "Ciência de curar doenças"
  , Entry "MEMORIA" "Capacidade de lembrar"
  , Entry "MERCADO" "Local de compra e venda"
  , Entry "MICROSCOPIO" "Instrumento para ver coisas pequenas"
  , Entry "MOTORISTA" "Pessoa que conduz veículo"
  , Entry "NASCIMENTO" "Ato de vir ao mundo"
  , Entry "NATUREZA" "Mundo natural não modificado"
  , Entry "NECESSIDADE" "Aquilo que é indispensável"
  , Entry "OCEANO" "Grande massa de água salgada"
  , Entry "OPORTUNIDADE" "Ocasião favorável"
  , Entry "ORGANIZACAO" "Estrutura sistemática"
  , Entry "PADARIA" "Local que vende pão"
  , Entry "PAISAGEM" "Vista de um lugar"
  , Entry "PASSADO" "Tempo que já se foi"
  , Entry "PACIENCIA" "Virtude de esperar com calma"
  , Entry "PENSAMENTO" "Atividade mental"
  , Entry "PERSONALIDADE" "Características individuais"
  , Entry "PIZZA" "Massa italiana com cobertura"
  , Entry "POLITICA" "Arte de governar"
  , Entry "POPULACAO" "Conjunto de habitantes"
  , Entry "PROBLEMA" "Situação difícil de resolver"
  , Entry "PROFESSOR" "Profissional do ensino"
  , Entry "QUALIDADE" "Grau de excelência"
  , Entry "QUANTIDADE" "Porção mensurável"
  , Entry "QUARTO" "Cômodo para dormir"
  , Entry "RADIO" "Aparelho de comunicação sonora"
  , Entry "REALIDADE" "Aquilo que existe de fato"
  , Entry "RECEITA" "Modo de preparo ou prescrição"
  , Entry "RELACIONAMENTO" "Conexão entre pessoas"
  , Entry "RELIGIAO" "Sistema de crenças espirituais"
  , Entry "RESPIRACAO" "Ato de respirar"
  , Entry "RESTAURANTE" "Estabelecimento que serve comida"
  , Entry "REVOLUCAO" "Mudança radical"
  , Entry "SABEDORIA" "Conhecimento profundo"
  , Entry "SAUDADE" "Sentimento de falta"
  , Entry "SEGURANCA" "Estado de proteção"
  , Entry "SILENCIO" "Ausência de som"
  , Entry "SOCIEDADE" "Grupo organizado de pessoas"
  , Entry "TECNOLOGIA" "Aplicação de conhecimento científico"
  , Entry "TELEVISAO" "Aparelho de transmissão de imagem"
  , Entry "TEMPERATURA" "Grau de calor ou frio"
  , Entry "TRANSPORTE" "Meio de locomoção"
  , Entry "UNIVERSIDADE" "Instituição de ensino superior"
  , Entry "VACINA" "Substância que previne doenças"
  , Entry "VELOCIDADE" "Rapidez de movimento"
  , Entry "VERDADE" "Aquilo que é real"
  , Entry "VETERINARIO" "Médico de animais"
  , Entry "VIAGEM" "Deslocamento a outro local"
  , Entry "VIOLENCIA" "Uso da força física"
  , Entry "VITAMINA" "Substância nutritiva essencial"
  , Entry "VOLUNTARIO" "Pessoa que trabalha sem pagamento"
  , Entry "XERIFE" "Autoridade policial local"
  , Entry "ZONA" "Área ou região específica"
  ]